In [15]:
import pandas as pd

In [52]:
import csv

with open('nasdaq-companies.csv') as csvfile:
    readCSV = csv.reader(csvfile, delimiter=';')
    ticker = []
    name = []
    sector = []
    for row in readCSV:
        ticker.append(row[0])
        name.append(row[1])
        sector.append(row[6])
        
with open('securities.csv') as basecsvfile:
    basereadCSV = csv.reader(basecsvfile, delimiter=',')
    for row in basereadCSV:
        if row[0] not in ticker:
            ticker.append(row[0])
            name.append(row[1])
            sector.append('')

d = {'Ticker' : ticker, 
    'Company' : name,
    'Sector' : sector}
        
df = pd.DataFrame(data=d)

df = df.drop([0])

df.sort_values(by='Ticker')

df

      Ticker                                     Company       Sector
1       WATT                        Energous Corporation   Technology
2       HSKA                           Heska Corporation  Health Care
3       TREE                           LendingTree, Inc.      Finance
4       PFIE                        Profire Energy, Inc.       Energy
5      CBMXW                     CombiMatrix Corporation  Health Care
...      ...                                         ...          ...
9753   ZXIET  IEX Test Company Test Symbol Three for IEX
9754  ZXYZ.A          Nasdaq Symbology Test Common Stock
9755   ZXZZT                           NASDAQ TEST STOCK
9756    ZYME                Zymeworks Inc. Common Shares
9757    ZYXI                  Zynex, Inc. - Common Stock

[9757 rows x 3 columns]

In [53]:
df = df.sort_values(by='Ticker', ascending=True)

df

      Ticker                                            Company       Sector
3195       A            Agilent Technologies, Inc. Common Stock
3196      AA                    Alcoa Corporation Common Stock
1127    AAAP             Advanced Accelerator Applications S.A.  Health Care
3197    AAAU                       Perth Mint Physical Gold ETF
3198    AACG  ATA Creativity Global - American Depositary Sh...
...      ...                                                ...          ...
9754  ZXYZ.A                 Nasdaq Symbology Test Common Stock
9755   ZXZZT                                  NASDAQ TEST STOCK
9756    ZYME                       Zymeworks Inc. Common Shares
830     ZYNE                      Zynerba Pharmaceuticals, Inc.  Health Care
9757    ZYXI                         Zynex, Inc. - Common Stock

[9757 rows x 3 columns]

In [54]:
df.to_csv('Companies By Sector.csv', index=False)